### PR TITLE
Added config option to "output" terminal to hide toolbar

### PR DESCRIPTION
**Pull request by thegecko**
In our plugin development, we don't want to display the toolbar on an `output` terminal.
This PR allows configuration of an `output` terminal to hide the toolbar with the addition of the `toolbar` boolean configuration option (default: true).

``` js
commands.exec("showoutput", null, {
    run: true,
    config: {
        runner: "my-runner",
        cwd: "/",
        debug: false,
        toolbar: false
    },
    callback: function(process, tab) {
        ...
    }
);
```

### CODE REVIEW

**Comment by thegecko** [comment]
@arekzaluski

**Comment by thegecko** [comment]
screen shot 2016-03-13 at 14 02 59

**Comment by nightwing** [comment]
looks good. merged as https://github.com/c9/c9.ide.run/commit/b0920c076d97861c65bd8004b1e5759ec2c2042d

**Comment by thegecko** [comment]
nice!

**Pull request closed without merging**
